# global settings
interval = 1

[[block]]
block = 'Volume'
interval = 20
update_on_signal = 'SIGUSR1'

[[block]]
block = 'Network'
title = 'VPN'
device = 'tun0'
template = "{{title}}{{totalDown}} at {{ipv4}}"

[[block]]
block = 'Network'
title = 'W'
device = 'wlp4s0'
template = "{{title}}{{bytesUp}} {{bytesDown}} of {{totalDown}} at {{ssid}} {{ipv4}}"

[[block]]
block = 'Network'
title = 'E'
device = 'enp0s31f6'
hide_if_down = true
template = "{{title}}{{bytesUp}} {{bytesDown}} of {{totalDown}} at {{ipv4}}"

[[block]]
block = 'Temperature'

[[block]]
block = 'CPU'

[[block]]
block = 'Memory'

[[block]]
block = 'Disk'
disk = '/dev/sda2'
interval = 5
sick_threshold = 20 # percentage

[[block]]
block = 'Battery'

[[block]]
block = 'DateTime'

